name: Notify

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  notify:
    name: Notify via Telegram
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
          TEMPLATE: '.[] | "<a href=\"\(.url)\">\(.id[:8])</a> • <a href=\"https://github.com/\(.author.username | @html)\">\(.author.username | @html)</a>

          \(.message | gsub("(?<a>[<>&\"])"; .a|@html))

          "'
        run: |
          (
            printenv COMMITS | jq -r "$TEMPLATE"
            printf '📅 @Persian_Calendar (persian-calendar/praytimes)'
          ) | \
          jq -R --slurp '{
            text: .,
            disable_web_page_preview: true,
            chat_id: "${{ secrets.TELEGRAM_CHAT_ID }}",
            parse_mode: "HTML"
          }' | \
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -H 'Content-Type: application/json' \
            --data-binary @-
